exports.seed = function(knex, Promise) {
  /* ALWAYS SEED CONTACTS FIRST, NEED ID'S TO SEED REFERENCE TABLE */
  const contactIdArray = async () => {
    return await knex.select("contact_id").from("contacts");
  };

  // Deletes ALL existing entries
  return knex("submissions")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("submissions").insert([
        {
          display_name: "testsubmission1",
          account_name: "testsubmission1",
          agency_number: "123456",
          mail_to_city: "mailToCity",
          mail_to_state: "OR",
          mail_to_street: "mail_to_street",
          mail_to_postal_code: "97221",
          first_name: "firstname1",
          last_name: "lastname1",
          dd: "01",
          mm: "01",
          yyyy: "2001",
          dob: new Date("01/01/2001"),
          preferred_language: "English",
          home_street: "homestreet",
          home_postal_code: "12345",
          home_state: "OR",
          home_city: "Portland",
          home_email: "fakeemail1@test.com",
          mobile_phone: "123-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar.png",
          online_campaign_source: "email",
          contact_id: contactIdArray[0].contact_id,
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("01/08/2003"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        },

        {
          display_name: "testsubmission2",
          account_name: "testsubmission2",
          agency_number: "234567",
          mail_to_city: "mailToCity",
          mail_to_state: "OR",
          mail_to_street: "mail_to_street_new",
          mail_to_postal_code: "123456",
          first_name: "firstname1",
          last_name: "lastname1",
          dd: "01",
          mm: "01",
          yyyy: "2001",
          dob: new Date("01/01/2001"),
          preferred_language: "English",
          home_street: "homestreet",
          home_postal_code: "123456",
          home_state: "OR",
          home_city: "Portland",
          home_email: "fakeemail1@test.com",
          mobile_phone: "123-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar.png",
          online_campaign_source: "email",
          contact_id: contactIdArray[0].contact_id,
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("01/08/2003"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        },

        {
          display_name: "testsubmission3",
          account_name: "testsubmission3",
          agency_number: "345678",
          mail_to_city: "mailToCity",
          mail_to_state: "OR",
          mail_to_street: "mail_to_street_new",
          mail_to_postal_code: "23456",
          first_name: "firstname2",
          last_name: "lastname2",
          dd: "02",
          mm: "02",
          yyyy: "2002",
          dob: new Date("02/02/2002"),
          preferred_language: "English",
          home_street: "homestreet",
          home_postal_code: "23456",
          home_state: "OR",
          home_city: "Portland",
          home_email: "fakeemail2@test.com",
          mobile_phone: "223-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar_2.png",
          online_campaign_source: "email",
          contact_id: contactIdArray[1].contact_id,
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("02/09/2004"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        }
      ]);
    });
};
