const uuid = require("uuid");

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("contacts")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("contacts").insert([
        {
          contact_id: uuid.v4(),
          display_name: "testcontact1",
          account_name: "testcontact1",
          agency_number: "123456",
          mail_to_city: "mailToCity",
          mail_to_state: "mail_to_state",
          mail_to_street: "mail_to_street",
          mail_to_postal_code: "23456",
          first_name: "firstname1",
          last_name: "lastname1",
          dd: "01",
          mm: "01",
          yyyy: "2001",
          dob: new Date("01/01/2001"),
          preferred_language: "English",
          home_street: "home_street",
          home_postal_code: "23456",
          home_state: "OR",
          home_city: "home_city",
          home_email: "fakeemail1@test.com",
          mobile_phone: "123-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar1.png",
          online_campaign_source: "email",
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("01/08/2003"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        },

        {
          contact_id: uuid.v4(),
          display_name: "testcontact2",
          account_name: "testcontact2",
          agency_number: "23456",
          mail_to_city: "mailToCity",
          mail_to_state: "mail_to_state",
          mail_to_street: "mail_to_street",
          mail_to_postal_code: "34567",
          first_name: "firstname2",
          last_name: "lastname2",
          dd: "02",
          mm: "02",
          yyyy: "2002",
          dob: new Date("02/02/2002"),
          preferred_language: "English",
          home_street: "home_street",
          home_postal_code: "34567",
          home_state: "OR",
          home_city: "home_city",
          home_email: "fakeemail2@test.com",
          mobile_phone: "223-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar2.png",
          online_campaign_source: "email",
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("02/09/2004"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        },

        {
          contact_id: uuid.v4(),
          display_name: "testcontact3",
          account_name: "testcontact3",
          agency_number: "34567",
          mail_to_city: "mailToCity",
          mail_to_state: "mail_to_state",
          mail_to_street: "mail_to_street",
          mail_to_postal_code: "45678",
          first_name: "firstname3",
          last_name: "lastname3",
          dd: "03",
          mm: "03",
          yyyy: "2003",
          dob: new Date("03/03/2003"),
          preferred_language: "English",
          home_street: "home_street",
          home_postal_code: "45678",
          home_state: "OR",
          home_city: "home_city",
          home_email: "fakeemail3@test.com",
          mobile_phone: "323-546-7890",
          text_auth_opt_out: false,
          terms_agree: true,
          signature: "http://example.com/avatar3.png",
          online_campaign_source: "email",
          signed_application: true,
          ethnicity: "other",
          lgbtq_id: false,
          trans_id: false,
          disability_id: false,
          deaf_or_hard_of_hearing: false,
          blind_or_visually_impaired: false,
          gender: "female",
          gender_other_description: "",
          gender_pronoun: "She/Her",
          job_title: "jobtitle",
          hire_date: new Date("03/10/2005"),
          worksite: "worksite",
          work_email: "lastnamef@seiu.com"
        }
      ]);
    });
};
